#  Guía Completa de NumPy en Python

**NumPy** (Numerical Python) es una biblioteca fundamental para el cálculo numérico en Python. Proporciona soporte para **arrays multidimensionales** y funciones matemáticas optimizadas.

---

## **1️⃣ ¿Qué es NumPy y Por Qué Usarlo?**

NumPy permite:
✔ **Manejar arreglos multidimensionales** (`ndarray`).  
✔ **Realizar operaciones matemáticas optimizadas**.  
✔ **Manipular datos de manera eficiente**.  
✔ **Usar funciones estadísticas y algebraicas avanzadas**.  

📌 **Instalar NumPy** (si no lo tienes instalado):
```bash
pip install numpy
```

📌 **Importar NumPy** en Python:
```python
import numpy as np
```

---

## **2️⃣ Creación de Arrays en NumPy**

Los arrays en NumPy son más rápidos y eficientes que las listas de Python.

### **🔹 Convertir una Lista en un `ndarray`**
```python
import numpy as np

lista = [1, 2, 3, 4, 5]
arr = np.array(lista)
print(arr)  # ✅ [1 2 3 4 5]
print(type(arr))  # ✅ <class 'numpy.ndarray'>
```

### **🔹 Arrays Multidimensionales**
```python
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
```
📌 **Salida:**
```
[[1 2 3]
 [4 5 6]]
```

### **🔹 Arrays de Zeros y Ones**
```python
zeros = np.zeros((3, 3))  # Matriz 3x3 de ceros
ones = np.ones((2, 4))  # Matriz 2x4 de unos
print(zeros, ones)
```

### **🔹 `arange()` y `linspace()`**
```python
arr1 = np.arange(0, 10, 2)  # [0 2 4 6 8]
arr2 = np.linspace(0, 5, 10)  # 10 valores equidistantes entre 0 y 5
```

### **🔹 Matriz Identidad (`eye()`)**
```python
identidad = np.eye(4)  # Matriz identidad 4x4
```

---

## **3️⃣ Propiedades de un `ndarray`**
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # ✅ (2, 3) → Dimensiones
print(arr.ndim)  # ✅ 2 → Número de dimensiones
print(arr.size)  # ✅ 6 → Número total de elementos
print(arr.dtype)  # ✅ int64 (depende del sistema)
```

---

## **4️⃣ Indexado y Slicing en NumPy**
```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])  # ✅ 20 (Acceder al segundo elemento)
print(arr[1:4])  # ✅ [20 30 40] (Slicing)
print(arr[::-1])  # ✅ [50 40 30 20 10] (Invertir array)
```

📌 **Indexado en Matrices**:
```python
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz[0, 1])  # ✅ 2 (Fila 0, columna 1)
print(matriz[:, 1])  # ✅ [2 5] (Segunda columna)
```

---

## **5️⃣ Operaciones Matemáticas con Arrays**

NumPy permite **realizar operaciones matemáticas vectorizadas** sin necesidad de bucles.

```python
arr = np.array([1, 2, 3, 4, 5])

print(arr + 10)  # ✅ [11 12 13 14 15]
print(arr * 2)  # ✅ [2 4 6 8 10]
print(arr ** 2)  # ✅ [1 4 9 16 25]
```

📌 **Operaciones entre Arrays**:
```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # ✅ [5 7 9]
print(arr1 * arr2)  # ✅ [4 10 18]
```

---

## **6️⃣ Funciones Matemáticas en NumPy**
```python
arr = np.array([0, np.pi / 2, np.pi])

print(np.sin(arr))  # ✅ Seno de cada elemento
print(np.log(arr + 1))  # ✅ Logaritmo natural (evitar log(0))
print(np.exp(arr))  # ✅ Exponencial e^x
```

📌 **Funciones Estadísticas**:
```python
print(np.mean(arr))  # ✅ Media
print(np.median(arr))  # ✅ Mediana
print(np.std(arr))  # ✅ Desviación estándar
```

---

## **7️⃣ Álgebra Lineal en NumPy**
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # ✅ Producto Matricial
print(np.linalg.det(A))  # ✅ Determinante de A
print(np.linalg.inv(A))  # ✅ Inversa de A
```

---

## **8️⃣ Generación de Números Aleatorios (`numpy.random`)**

### **🔹 Generar un Número Aleatorio**
```python
print(np.random.rand())  # ✅ Número aleatorio entre 0 y 1
```

### **🔹 Generar un Array Aleatorio**
```python
print(np.random.rand(3, 3))  # ✅ Matriz 3x3 de números entre 0 y 1
```

### **🔹 Números Enteros Aleatorios**
```python
print(np.random.randint(1, 100, (3, 3)))  # ✅ Matriz 3x3 de enteros entre 1 y 100
```

---

## **9️⃣ Manipulación de Arrays**

### **🔹 Transponer una Matriz**
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)  # ✅ Transpuesta
```

### **🔹 Apilar Arrays**
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))  # ✅ Apilar verticalmente
print(np.hstack((a, b)))  # ✅ Apilar horizontalmente
```

---

## **🔟 Guardar y Cargar Arrays**

```python
np.save("array.npy", arr)  # Guardar
cargado = np.load("array.npy")  # Cargar
print(cargado)
```

---

## **🚀 Conclusión**

✔ **NumPy permite manejar arrays de manera eficiente.**  
✔ **Optimiza cálculos matemáticos y algebraicos.**  
✔ **Incluye funciones estadísticas y aleatorias avanzadas.**  
✔ **Facilita manipulación de datos en machine learning y ciencia de datos.**  


##  Guía DEFINITIVA de Pandas en Python

**Pandas** es una biblioteca fundamental para **análisis y manipulación de datos** en Python.  
Permite **cargar, transformar, analizar, limpiar y visualizar datos** de manera eficiente.

---

# **1️⃣ Instalación e Importación de Pandas**

📌 **Instalar Pandas** (si no lo tienes instalado):
```bash
pip install pandas
```

📌 **Importar Pandas** en Python:
```python
import pandas as pd
```

---

# **2️⃣ Creación de DataFrames y Series en Pandas**

📌 **Crear una `Series` (unidimensional):**
```python
serie = pd.Series([10, 20, 30, 40, 50])
print(serie)
```

📌 **Crear un `DataFrame` (bidimensional):**
```python
datos = {"Nombre": ["Ana", "Luis", "Carlos"], "Edad": [25, 30, 35]}
df = pd.DataFrame(datos)
print(df)
```

---

# **3️⃣ Lectura y Escritura de Archivos en Pandas**

📌 **Leer archivos**:
```python
df = pd.read_csv("datos.csv")  # Leer CSV
df = pd.read_excel("datos.xlsx")  # Leer Excel
df = pd.read_json("datos.json")  # Leer JSON
```

📌 **Guardar archivos**:
```python
df.to_csv("salida.csv", index=False)  # Guardar CSV
df.to_excel("salida.xlsx", index=False)  # Guardar Excel
```

---

# **4️⃣ Filtros en DataFrames**

📌 **Filtrar datos según una condición**:
```python
df_filtrado = df[df["Edad"] > 30]
```

📌 **Filtrar con múltiples condiciones**:
```python
df_filtrado = df[(df["Edad"] > 30) & (df["Ciudad"] == "Madrid")]
```

---

# **5️⃣ Cambiar Tipos de Datos**

📌 **Convertir una columna a otro tipo de dato**:
```python
df["Edad"] = df["Edad"].astype(float)
```

📌 **Convertir una fecha a formato datetime**:
```python
df["Fecha"] = pd.to_datetime(df["Fecha"])
```

---

# **6️⃣ Concatenación y Merge de DataFrames**

📌 **Concatenar DataFrames**:
```python
df_nuevo = pd.concat([df1, df2])
```

📌 **Unir DataFrames (`merge()`)**:
```python
df_merge = df1.merge(df2, on="ID", how="inner")
```

---

# **7️⃣ Métodos `.map()`, `.applymap()` y `.apply()`**

📌 **Transformar valores con `map()`**:
```python
df["Genero"] = df["Genero"].map({"M": 1, "F": 0})
```

📌 **Aplicar una función a una columna con `apply()`**:
```python
df["Edad_Doble"] = df["Edad"].apply(lambda x: x * 2)
```

📌 **Aplicar una función a todo el DataFrame con `applymap()`**:
```python
df = df.applymap(lambda x: x.upper() if isinstance(x, str) else x)
```

---

# **8️⃣ Manipulación de NaN (Valores Nulos)**

📌 **Eliminar Filas con NaN**:
```python
df_clean = df.dropna()
```

📌 **Rellenar NaN con un Valor**:
```python
df.fillna(0, inplace=True)
```

---

# **9️⃣ Encoding en Pandas**

Los modelos de machine learning requieren datos **numéricos**, por lo que es necesario **convertir variables categóricas** en números. Este proceso se llama **Encoding**.

## **1️⃣0️⃣ One-Hot Encoding (`get_dummies()`)**
✔ **Útil para variables categóricas sin orden**  
✔ **Crea una columna para cada categoría con 0 o 1**  

```python
df_encoded = pd.get_dummies(df, columns=["Ciudad"], drop_first=True)
```

📌 **Ejemplo**:
```
      Ciudad  Ciudad_Barcelona  Ciudad_Madrid  Ciudad_Sevilla
0    Madrid                0              1               0
1  Barcelona               1              0               0
2   Sevilla                0              0               1
```

## **1️⃣1️⃣ Label Encoding (`LabelEncoder()`)**
✔ **Asigna un número único a cada categoría**  
✔ **Útil para variables ordinales (con orden lógico)**  

```python
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["Genero_encoded"] = encoder.fit_transform(df["Genero"])
```

📌 **Ejemplo**:
```
  Genero  Genero_encoded
0      M               1
1      F               0
2      F               0
3      M               1
```

## **1️⃣2️⃣ Ordinal Encoding (`OrdinalEncoder()`)**
✔ **Útil para variables con jerarquía (pequeño < mediano < grande)**  

```python
from sklearn.preprocessing import OrdinalEncoder

orden = OrdinalEncoder(categories=[["Pequeño", "Mediano", "Grande"]])
df["Talla_encoded"] = orden.fit_transform(df[["Talla"]])
```

📌 **Ejemplo**:
```
         Talla  Talla_encoded
0    Pequeño            0.0
1    Grande            2.0
2   Mediano            1.0
```

## **1️⃣3️⃣ Target Encoding (Mean Encoding)**
✔ **Usa la media de la variable objetivo para codificar categorías**  
✔ **Útil en modelos de árboles como XGBoost y Random Forest**  

```python
df["Ciudad_encoded"] = df.groupby("Ciudad")["Salario"].transform("mean")
```

📌 **Ejemplo**:
```
      Ciudad  Ciudad_encoded
0    Madrid           3100.0
1  Barcelona          2650.0
2   Sevilla           2700.0
```

## **1️⃣4️⃣ Hash Encoding (Feature Hashing)**
✔ **Reduce dimensionalidad cuando hay muchas categorías**  

```python
from sklearn.feature_extraction import FeatureHasher

fh = FeatureHasher(n_features=3, input_type="string")
hashed_features = fh.fit_transform(df["Ciudad"])
print(hashed_features.toarray())
```

📌 **Ejemplo**:
```
[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
```

---

# **🚀 Conclusión**

✔ **Pandas permite manejar y analizar datos de manera eficiente.**  
✔ **Ofrece múltiples formas de codificar variables categóricas.**  
✔ **Cada técnica de Encoding tiene ventajas y desventajas según el tipo de variable.**  
✔ **One-Hot Encoding es ideal para datos sin orden, mientras que Label Encoding es mejor para datos ordinales.**  
✔ **Target Encoding y Hash Encoding son útiles para modelos avanzados.**  