## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==1.26.4


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [3]:
matriz =np.array([[1,2,3], [1,2,3]])
print(matriz)
print(matriz.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [10]:
matriz = list()
for i in range(4):
    filas = []
    for j in range(4):
        # num_aleatorio = i
        # num_aleatorio = j
        num_aleatorio = random.randint(1, 100)
        filas.append(num_aleatorio)
        
    matriz.append(filas)
    
np.array(matriz)

array([[68, 85, 23,  3],
       [74, 87, 67, 94],
       [24, 53, 75, 34],
       [64, 55, 82, 56]])

### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [16]:
def gen_matriz(m, n):
    matriz = []
    if m <= 0 or n<= 0:
        raise ValueError("Dimensiones incorrectas") # Generamos un error por si meten datos incorrectos
    for i in range(m):
        filas = []
        for j in range(n):
            num_aleatorio = random.randint(1, 100)
            filas.append(num_aleatorio)
        
        matriz.append(filas)
    return np.array(matriz)

gen_matriz(4, 8)

array([[52, 53, 58, 67, 70, 13, 47,  4],
       [93, 83, 91, 32, 23, 72,  1, 32],
       [35, 64, 91, 32, 50, 33, 36,  1],
       [77, 20, 25, 30, 51, 53,  1, 89]])

In [ ]:
##############################################################################################################################