## Ejercicios - NumPy 1

In [1]:
import numpy as np

In [2]:
# Versión
print(f"numpy=={np.__version__}")

numpy==1.26.4


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [7]:
array_pares = np.array([i for i in range(2, 12, 2)])
array_pares

array([ 2,  4,  6,  8, 10])

In [10]:
array_impares = np.array([i for i in range(1, 11, 2)])
array_impares

array([1, 3, 5, 7, 9])

In [11]:
# Concatenate y reshape. POr defecto es axis=0 ya que el vector es de una dimension
numbers = np.concatenate((array_pares, array_impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [13]:
matriz_5x2 = numbers.reshape(5,2)
matriz_5x2

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [14]:
matriz_5x2.dtype

dtype('int64')

In [4]:
import pandas as pd

In [5]:
print(f"pandas=={pd.__version__}")

pandas==2.2.2


### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

### Ejercico 11:
- Obten la tercera columna de la matriz.

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [ ]:
################################################################################################################################